version: 0.0
os: windows
files:
  - source: \
    destination: c:\AppFolder
hooks:
  ApplicationStop:
    - location: stopService.bat
      timeout: 180
  ApplicationStart:
    - location: startService.bat
      timeout: 180
