version: 0.0
os: windows
files:
  - source: /JAWTAccessBridge-32.dll
    destination: c:\AppFolder
hooks:
  ApplicationStop:
    - location: stopService.bat
      timeout: 180
    - location: removeService.bat
      timeout: 180
  AfterInstall:
    - location: installService.bat
      timeout: 180
  ApplicationStart:
    - location: startService.bat
      timeout: 180
