version: 0.0
os: windows
files:
  - source: /JAWTAccessBridge-32.dll
    destination: c:\AppFolder
hooks:
  ApplicationStop:
    - location: c:\java-wrapper\removeService.bat
      timeout: 180
  AfterInstall:
    - location: c:\java-wrapper\installService.bat
      timeout: 180
  ApplicationStart:
    - location: c:\java-wrapper\startService.bat
      timeout: 180
