version: 0.0
os: windows
files:
  - source: /ReadMe.txt
    destination: c:\AppFolder
hooks:
  ApplicationStop:
    - location: c:\java-wrapper\stopService.bat
      timeout: 180
    - location: c:\java-wrapper\removeService.bat
      timeout: 180
  AfterInstall:
    - location: c:\java-wrapper\installService.bat
      timeout: 180
  ApplicationStart:
    - location: c:\java-wrapper\startService.bat
      timeout: 3600
